# MC3-Project-1 Learners

In [56]:
from DataHelper import DataHelper 

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm
import scipy.optimize as spo

from sklearn import datasets
from sklearn import tree
from sklearn.model_selection import train_test_split

In [4]:
# RTLearner Random Tree Learner
df = pd.read_csv('data/winequality-red.csv', delimiter=";")

In [61]:
df.sort_values(['quality'], ascending=False)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
495            10.7             0.350         0.53            2.60      0.070   
1403            7.2             0.330         0.33            1.70      0.061   
390             5.6             0.850         0.05            1.40      0.045   
1061            9.1             0.400         0.50            1.80      0.071   
1202            8.6             0.420         0.39            1.80      0.068   
828             7.8             0.570         0.09            2.30      0.065   
481             9.4             0.300         0.56            2.80      0.080   
455            11.3             0.620         0.67            5.20      0.086   
1449            7.2             0.380         0.31            2.00      0.056   
440            12.6             0.310         0.72            2.20      0.072   
1549            7.4             0.360         0.30            1.80      0.074   
498            10.7             0.350         0.53            2.60      0.070   
267             7.9             0.350         0.46            3.60      0.078   
1269            5.5             0.490         0.03            1.80      0.044   
278            10.3             0.320         0.45            6.40      0.073   
1120            7.9             0.540         0.34            2.50      0.076   
588             5.0             0.420         0.24            2.00      0.060   
1090           10.0             0.260         0.54            1.90      0.083   
488            11.6             0.320         0.55            2.80      0.081   
491             9.2             0.410         0.50            2.50      0.055   
996             5.6             0.660         0.00            2.20      0.087   
1132            7.4             0.360         0.34            1.80      0.075   
492             8.9             0.400         0.51            2.60      0.052   
357            10.5             0.420         0.66            2.95      0.116   
1133            7.2             0.480         0.07            5.50      0.089   
1134            8.5             0.280         0.35            1.70      0.061   
896             8.3             0.310         0.39            2.40      0.078   
887            10.7             0.520         0.38            2.60      0.066   
901             7.4             0.635         0.10            2.40      0.080   
902             7.4             0.635         0.10            2.40      0.080   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00            2.10      0.060   
73              8.3             0.675         0.26            2.10      0.084   
161             7.6             0.680         0.02            1.30      0.072   
724             7.5             1.115         0.10            3.10      0.086   
1176            6.5             0.880         0.03            5.60      0.079   
1423            6.4             0.530         0.09            3.90      0.123   
1233           10.2             0.230         0.37            2.20      0.057   
937            12.0             0.630         0.50            1.40      0.071   
41              8.8             0.610         0.30            2.80      0.088   
1235            6.0             0.330         0.32           12.90      0.054   
151             9.2             0.520         1.00            3.40      0.610   
1238            8.1             0.730         0.00            2.50      0.081   
45              4.6             0.520         0.15            2.10      0.054   
1239            6.5             0.670         0.00            4.30      0.057   
813             6.9             0.390         0.24            2.10      0.102   
703             7.5             0.380         0.48            2.60      0.073   
704             9.1             0.765         0.04            1.60      0.078   
1521            6.9             0.480

In [10]:
data = datasets.load_wine()

In [14]:
print( data.DESCR)

Wine Data Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- 1) Alcohol
 		- 2) Malic acid
 		- 3) Ash
		- 4) Alcalinity of ash  
 		- 5) Magnesium
		- 6) Total phenols
 		- 7) Flavanoids
 		- 8) Nonflavanoid phenols
 		- 9) Proanthocyanins
		- 10)Color intensity
 		- 11)Hue
 		- 12)OD280/OD315 of diluted wines
 		- 13)Proline
        	- class:
                - class_0
                - class_1
                - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash: 

In [17]:
data.feature_names
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
# correlation matrix
df.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.256131     0.671703   
volatile acidity          -0.256131          1.000000    -0.552496   
citric acid                0.671703         -0.552496     1.000000   
residual sugar             0.114777          0.001918     0.143577   
chlorides                  0.093705          0.061298     0.203823   
free sulfur dioxide       -0.153794         -0.010504    -0.060978   
total sulfur dioxide      -0.113181          0.076470     0.035533   
density                    0.668047          0.022026     0.364947   
pH                        -0.682978          0.234937    -0.541904   
sulphates                  0.183006         -0.260987     0.312770   
alcohol                   -0.061668         -0.202288     0.109903   
quality                    0.124052         -0.390558     0.226373   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.114777   0.093705            -0.153794   
volatile acidity            0.001918   0.061298            -0.010504   
citric acid                 0.143577   0.203823            -0.060978   
residual sugar              1.000000   0.055610             0.187049   
chlorides                   0.055610   1.000000             0.005562   
free sulfur dioxide         0.187049   0.005562             1.000000   
total sulfur dioxide        0.203028   0.047400             0.667666   
density                     0.355283   0.200632            -0.021946   
pH                         -0.085652  -0.265026             0.070377   
sulphates                   0.005527   0.371260             0.051658   
alcohol                     0.042075  -0.221141            -0.069408   
quality                     0.013732  -0.128907            -0.050656   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.113181  0.668047 -0.682978   0.183006   
volatile acidity                  0.076470  0.022026  0.234937  -0.260987   
citric acid                       0.035533  0.364947 -0.541904   0.312770   
residual sugar                    0.203028  0.355283 -0.085652   0.005527   
chlorides                         0.047400  0.200632 -0.265026   0.371260   
free sulfur dioxide               0.667666 -0.021946  0.070377   0.051658   
total sulfur dioxide              1.000000  0.071269 -0.066495   0.042947   
density                           0.071269  1.000000 -0.341699   0.148506   
pH                               -0.066495 -0.341699  1.000000  -0.196648   
sulphates                         0.042947  0.148506 -0.196648   1.000000   
alcohol                          -0.205654 -0.496180  0.205633   0.093595   
quality                          -0.185100 -0.174919 -0.057731   0.251397   

                       alcohol   quality  
fixed acidity        -0.061668  0.124052  
volatile acidity     -0.202288 -0.390558  
citric acid           0.109903  0.226373  
residual sugar        0.042075  0.013732  
chlorides            -0.221141 -0.128907  
free sulfur dioxide  -0.069408 -0.050656  
total sulfur dioxide -0.205654 -0.185100  
density              -0.496180 -0.174919  
pH                    0.205633 -0.057731  
sulphates             0.093595  0.251397  
alcohol               1.000000  0.476166  
quality               0.476166  1.000000

In [22]:
# linear regression
X = df["alcohol"]
y = df["quality"]

#X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
predictions = model.predict(X)

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                quality   R-squared:                       0.983
Model:                            OLS   Adj. R-squared:                  0.983
Method:                 Least Squares   F-statistic:                 9.427e+04
Date:                Thu, 03 May 2018   Prob (F-statistic):               0.00
Time:                        21:17:40   Log-Likelihood:                -1776.7
No. Observations:                1599   AIC:                             3555.
Df Residuals:                    1598   BIC:                             3561.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
alcohol        0.5389      0.002    307.038      0.000         0.535     0.542
==============================================================================
Omnibus:                       70.936   Durbin-Watson:                   1.707
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              129.332
Skew:                          -0.332   Prob(JB):                     8.24e-29
Kurtosis:                       4.225   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
np.corrcoef(X, y)

array([[ 1.        ,  0.47616632],
       [ 0.47616632,  1.        ]])

In [35]:
# set X data
X = df.ix[:,0:-1]
X.head()


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [41]:
# set y data
y = df.ix[:,-1]
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [44]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,y)

In [53]:
clf.predict(X[0:5])

array([5, 5, 5, 6, 5], dtype=int64)

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [62]:
clf = clf.fit(X_train, y_train)

In [63]:
clf.predict(X_test)

array([5, 5, 5, 3, 6, 6, 5, 6, 5, 5, 5, 5, 7, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6,
       6, 4, 6, 7, 5, 7, 6, 5, 6, 6, 5, 6, 7, 5, 5, 5, 5, 6, 7, 6, 7, 6, 7,
       5, 5, 6, 6, 6, 7, 6, 5, 5, 5, 5, 5, 7, 6, 6, 6, 5, 5, 5, 6, 6, 6, 7,
       5, 5, 6, 5, 7, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 7, 5, 5, 5, 5, 5,
       6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 7, 5, 6, 5, 4, 5, 5, 4, 6, 6, 4, 6, 5,
       6, 6, 6, 6, 6, 7, 7, 6, 5, 6, 6, 7, 5, 5, 8, 6, 5, 6, 5, 5, 6, 6, 6,
       7, 5, 6, 5, 6, 5, 6, 7, 6, 5, 8, 6, 5, 3, 5, 6, 6, 6, 7, 6, 5, 6, 5,
       6, 5, 5, 6, 5, 6, 5, 7, 5, 7, 4, 6, 7, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5,
       5, 5, 5, 5, 5, 6, 7, 4, 6, 6, 5, 6, 6, 7, 5, 6, 6, 5, 5, 6, 5, 7, 5,
       5, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 7, 5, 5, 6, 6,
       6, 6, 6, 5, 4, 5, 6, 5, 5, 6, 5, 6, 6, 4, 5, 5, 5, 6, 7, 5, 5, 6, 6,
       5, 5, 6, 5, 5, 5, 6, 4, 6, 6, 6, 6, 5, 5, 7, 8, 5, 6, 7, 5, 5, 6, 6,
       6, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 8, 7, 7, 5, 7, 6, 6, 7, 7, 6, 7, 6,
       5, 5,

In [64]:
y_test

573     4
808     5
655     5
166     5
816     6
1330    6
1433    7
1291    6
604     6
1245    5
223     6
1072    6
1058    7
191     6
165     5
401     6
679     5
265     7
280     6
1154    6
1400    5
1268    6
726     6
1254    5
95      6
1412    6
354     6
629     5
730     5
876     4
       ..
894     6
610     5
152     5
414     5
597     6
1191    5
1469    3
1189    4
340     6
1393    5
879     5
756     6
1590    6
965     6
1094    6
609     6
78      5
1149    6
1571    6
231     6
601     6
698     5
1578    6
479     6
1259    6
1350    5
1095    5
1265    6
1499    6
733     5
Name: quality, dtype: int64

In [86]:
from sklearn.model_selection import cross_val_score
clf = tree.DecisionTreeClassifier()
cross_val_score(clf, X, y, scoring="accuracy")

array([ 0.44672897,  0.41463415,  0.47834275])

In [90]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(10)
cross_val_score(clf, X, y, scoring="accuracy")

array([ 0.48598131,  0.55909944,  0.55555556])